[package]
name = "rustml"
version = "0.1.0"
edition = "2021"


[dependencies]
rand = "0.8.5"
libloading = "0.8.3"
serde_json = "1.0.120"
serde = { version = "1.0.204", features = ["derive"] }


[[bin]]
name = "rustml"
path = "src/main.rs"

[profile.release]
debug = true

